name: Linux Build

on:
  push:
    branches: [ "master", "main", "feat/*" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential tar curl zip unzip pkg-config autoconf libtool autoconf-archive bison flex
        sudo apt-get install -y libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev libflac-dev libogg-dev libvorbis-dev libopenal-dev libxcursor-dev ninja-build

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Configure CMake
      # Override toolchain file to use the one provided by the action
      run: cmake --preset linux-release -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build --preset linux-release

    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: r-type_client-linux
        path: build/linux-release/r-type_client

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: r-type_server-linux
        path: build/linux-release/r-type_server
