name: Windows Build

on:
  push:
    branches: [ "master", "main", "feat/*" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Configure CMake
      # Override toolchain file to use the one provided by the action
      run: cmake --preset windows-release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build --preset windows-release

    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: r-type_client-windows
        path: build/windows-release/r-type_client.exe

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: r-type_server-windows
        path: build/windows-release/r-type_server.exe
